[build]
  functions = "netlify/functions"
  publish = "docs"

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  functions = "netlify/functions"
  publish = "docs"
